# Generated by Django 5.1.1 on 2024-09-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='TITLE', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='DESCRIPTIONS', null=True)),
                ('location', models.TextField(blank=True, db_column='LOCATION', null=True)),
                ('operating_hours', models.CharField(blank=True, db_column='OPERATING_HOURS', max_length=255, null=True)),
                ('entrance_fee', models.CharField(blank=True, db_column='ENTRANCE_FEE', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tourist_images/')),
                ('parking', models.CharField(blank=True, db_column='parking', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tourist',
                'managed': True,
            },
        ),
    ]
